spring:
  application:
    name: seniority-meter
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_POSTGRESQL_HOST:localhost}:${DB_POSTGRESQL_PORT:5432}/${DB_POSTGRESQL_NAME:portfoliodeveloper}
    username: ${DB_POSTGRESQL_USER:portfoliodeveloper}
    password: ${DB_POSTGRESQL_PASS:portfoliodeveloper}
  flyway:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_POSTGRESQL_HOST:localhost}:${DB_POSTGRESQL_PORT:5432}/${DB_POSTGRESQL_NAME:portfoliodeveloper}
    user: ${DB_POSTGRESQL_USER:portfoliodeveloper}
    password: ${DB_POSTGRESQL_PASS:portfoliodeveloper}
    baseline-on-migrate: true
  notification:
    email:
      enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
      host: ${NOTIFICATION_EMAIL_HOST:smtp.gmail.com}
      port: ${NOTIFICATION_EMAIL_PORT:587}
      username: ${NOTIFICATION_EMAIL_USERNAME}
      password: ${NOTIFICATION_EMAIL_PASSWORD}