spring:
  application:
    name: seniority-meter
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_POSTGRESQL_HOST:localhost}:${DB_POSTGRESQL_PORT:5432}/${DB_POSTGRESQL_NAME:portfoliodeveloper}
    username: ${DB_POSTGRESQL_USER:portfoliodeveloper}
    password: ${DB_POSTGRESQL_PASS:portfoliodeveloper}
  flyway:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_POSTGRESQL_HOST:localhost}:${DB_POSTGRESQL_PORT:5432}/${DB_POSTGRESQL_NAME:portfoliodeveloper}
    user: ${DB_POSTGRESQL_USER:portfoliodeveloper}
    password: ${DB_POSTGRESQL_PASS:portfoliodeveloper}
    baseline-on-migrate: true
  notification:
    email:
      enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
      host: ${NOTIFICATION_EMAIL_HOST:smtp.gmail.com}
      port: ${NOTIFICATION_EMAIL_PORT:587}
      username: ${NOTIFICATION_EMAIL_USERNAME:username}
      password: ${NOTIFICATION_EMAIL_PASSWORD:password}
  documentation:
    contact:
      name: Luiz Fernando Oliveira
      email: luizfernandesoliveiraoficial@contaazul.com
    info:
      title: Portfolio Developer
      description: API to portfolio for a developer
      version: 1.0.0
      termsOfService: https://www.apache.org/licenses/LICENSE-2.0
    license:
      name: Apache License 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0
  security:
    jwt:
      secret: ${SECURITY_JWT_SECRET:4885702d-3b3f-4b2e-9fc3-0022fc2bfee6}