### Auth SignUp
POST http://localhost:8080/api/v1/sign-up
Accept: application/json
Content-Type: application/json

{
  "name": "Luiz Fernandes Oliveira",
  "email": "luizfernandesoliveiraoficial@gmail.com",
  "pdi": "123123123123",
  "phone": "11999999999"
}

### Auth SignIn
POST http://localhost:8080/api/v1/sign-in
Accept: application/json
Content-Type: application/json

{
  "email": "luizfernandesoliveiraoficial@gmail.com"
}

### Auth SignConfirm
POST http://localhost:8080/api/v1/sign-confirm
Accept: application/json
Content-Type: application/json

{
  "email": "luizfernandesoliveiraoficial@gmail.com",
  "code": "582465"
}